### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by bardiukz** [lucasbuyatti/Ext#1]
Hola, te dejo unos tips chotos pero tips xd, si hace poco estas con c++ no debes saber q son los threads, pero te servirian para hacer que algunas features corran por su thread sin interferir con las otras, ademas de mejorar el performance un monton ya que cada una puede tener un yield/sleep y no va a interferir con la aplicacion principal o las demas features
Un ejemplo donde podrias utilizar un thread aparte: [main.cpp](https://github.com/lucasbuyatti/Ext/blob/master/main.cpp#L26)

Otra cosa, estas variables no tenes q dejarlas fuera, pq una vez cambias de mapa o tu local x algun motivo se vuelve null, podrias tener crasheos [10](https://github.com/lucasbuyatti/Ext/blob/master/features.h#L10), [12](https://github.com/lucasbuyatti/Ext/blob/master/features.h#L12), [14](https://github.com/lucasbuyatti/Ext/blob/master/features.h#L14), lo mejor seria llamarlas a cada una en cada feature denuevo ya que el consumo es minimo o hacer un thread que sea solo para obtener data y guardarla en una struct

**Comment by lucasbuyatti** [comment]
Hace un tiempo vengo haciendo clases en las que solo se ejecutaba la primera declaración, pero me salvaste, quedo algo así, espero que este bien

![Screenshot 2022-02-18 150713](https://user-images.githubusercontent.com/80955148/154738314-88930b81-569f-465c-9421-e9d12ed975ab.png)
